[package]
name = "paekli-cli"
version = "0.1.3"
edition = "2021"
repository = "https://github.com/wegmanma/rust-workshop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
